--CASE STATEMENTS
--Type of case statements

--SIMPLE CASE STATEMENT:
--      CASE EXPRESSION
--      WHEN VALUE THEN STATEMENT
--      WHEN VALUE THEN STATMENNT
--      ...
--      END;

SET SERVEROUT ON
DECLARE
    v_number number := 10;
BEGIN
    CASE MOD(v_number,2)
        WHEN 0 THEN DBMS_OUTPUT.PUT_LINE(v_number || ' IS AN EVEN NUMBER'); 
        ELSE DBMS_OUTPUT.PUT_LINE(v_number || ' IS AN ODD NUMBER');
    END CASE;
        
END;
/

--SEARCHED CASE STATEMENT:
--CASE
--WHEN EXPRESSION THEN STATMENT/EXPRESSION
--WHEN EXPRESSION THEN STATMENT/EXPRESSION
--....
--END;

DECLARE 
    v_number NUMBER := 11;
BEGIN
    CASE
    WHEN MOD(v_number,2)= 0 THEN 
        DBMS_OUTPUT.PUT_LINE(v_number || ' IS AN EVEN NUMBER');
    WHEN MOD(v_number,2)= -1 THEN
        DBMS_OUTPUT.PUT_LINE(v_number || ' INVALID DATA');
    ELSE
        DBMS_OUTPUT.PUT_LINE(v_number || ' IS AN ODD NUMBER'); 
    END CASE;
END;
/












