--GOTO STATEMENTS
--ITS A CONDITIONAL FLOW STATEMENT
--USING THE GOTO STATEMENT WE CAN DIVERT THE NATURAL FLOW OF OUR PROGRAM
--GOTO STATEMENT IS USED WITH LABEL
--THEN USING GOTO WE WILL JUMP TO THAT LABEL.

SET SERVEROUT ON;
DECLARE
    V_NUM NUMBER :=15;
BEGIN
    <<START_OF_THE_PROCEDURE>>
    DBMS_OUTPUT.PUT_LINE('V_NUM = ' || V_NUM);
    V_NUM := V_NUM+5;
    IF V_NUM <= 30 THEN
        GOTO START_OF_THE_PROCEDURE;
    END IF;
END;
/
--GOTO statement should not interface the flow of other conditional flow.

--SYNTAX:
    --LABEL: <<label_name>>
    -- GOTO statement: GOTO lable_name








