CREATE TABLE emp_2 (
    emp_name    VARCHAR(20),
    emp_id      NUMBER(5),
    ta          NUMBER(15),
    da          NUMBER(15),
    total       NUMBER(20),
    branch_city VARCHAR(15)
)

INSERT INTO EMP_2 VALUES('ABC', 10, 1200, 1340, NULL, 'LAHORE');
INSERT INTO EMP_2 VALUES('XYZ', 11, 1300, 1200, NULL, 'KARACHI');
INSERT INTO EMP_2 VALUES('DEF', 12, 1500, 1640, NULL, 'ISLAMABAD');

SELECT * FROM EMP_2;

DECLARE
    A NUMBER(10);
    B NUMBER(10);
    T NUMBER(15);
BEGIN
    SELECT TA, DA INTO A, B FROM EMP_2 WHERE EMP_ID = 10;
    T := A + B;
    UPDATE EMP_2 SET TOTAL = T WHERE EMP_ID = 10;
END;
/

DECLARE
    A EMP_2.TA%TYPE;
    B EMP_2.DA%TYPE;
    T EMP_2.TOTAL%TYPE;
BEGIN
    SELECT TA, DA INTO A, B FROM EMP_2 WHERE EMP_ID = 11;
    T := A + B;
    
    UPDATE EMP_2 SET TOTAL = T WHERE EMP_ID = 11;
END;
/

DECLARE
    A EMP_2.TA%TYPE;
    B EMP_2.DA%TYPE;
    T EMP_2.TOTAL%TYPE;
    I NUMBER :=10;
BEGIN
    WHILE I <=12
    LOOP
        SELECT TA, DA INTO A, B FROM EMP_2 WHERE EMP_ID = I;
        T := A + B;
        UPDATE EMP_2 SET TOTAL = T WHERE EMP_ID = I;
        I := I + 1;
    END LOOP;
END;
/



