SET SERVEROUT ON;
--PACKAGE SPECIFICATION
CREATE OR REPLACE PACKAGE PKG_FOR_PRACTICE AS
    V_DEPT_EMP_CNT         NUMBER;
    V_IS_SALARY_HIGH_THEN_DEPT_SALARY VARCHAR2 (10);
    
--PROCEDURES
    PROCEDURE MULTIPLICATION(
        NUM1 IN NUMBER, 
        NUM2 IN NUMBER, 
        MUL OUT NUMBER
        );
    PROCEDURE P_SECOND_HEIGHET_SAL_EMP(
        P_IN_DEP_ID IN DEPARTMENTS.DEPARTMENT_ID%TYPE,
        P_OUT_EMP_ID OUT EMPLOYEES.EMPLOYEE_ID%TYPE,
        P_OUT_EMP_NAME OUT EMPLOYEES.FIRST_NAME%TYPE,
        P_OUT_EMP_SALARY OUT EMPLOYEES.SALARY%TYPE,
        P_OUT_STATUS OUT NUMBER
        );
--FUNCTIONS
    FUNCTION FUN_IS_SALARAY_ABOVE_AVG_DEPT_SALARY(
        P_IN_EMP_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE
        ) RETURN VARCHAR2;
END PKG_FOR_PRACTICE;

--PACKAGE BODY
CREATE OR REPLACE PACKAGE BODY PKG_FOR_PRACTICE AS
    PROCEDURE MULTIPLICATION(
        NUM1 IN NUMBER, 
        NUM2 IN NUMBER, 
        MUL OUT NUMBER
        )IS
        BEGIN
            MUL:= NUM1 * NUM2;
        END MULTIPLICATION;
        
    PROCEDURE P_SECOND_HEIGHET_SAL_EMP(
        P_IN_DEP_ID IN DEPARTMENTS.DEPARTMENT_ID%TYPE,
        P_OUT_EMP_ID OUT EMPLOYEES.EMPLOYEE_ID%TYPE,
        P_OUT_EMP_NAME OUT EMPLOYEES.FIRST_NAME%TYPE,
        P_OUT_EMP_SALARY OUT EMPLOYEES.SALARY%TYPE,
        P_OUT_STATUS OUT NUMBER
        ) IS
        BEGIN
            P_OUT_STATUS:= 0;
            SELECT COUNT(1) INTO V_DEPT_EMP_CNT FROM EMPLOYEES WHERE DEPARTMENT_ID = P_IN_DEP_ID;
            IF V_DEPT_EMP_CNT < 2 THEN
                P_OUT_STATUS := -1;
            ELSE 
                SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
                INTO P_OUT_EMP_ID, P_OUT_EMP_NAME, P_OUT_EMP_SALARY
                FROM EMPLOYEES
                WHERE DEPARTMENT_ID = P_IN_DEP_ID
                ORDER BY SALARY DESC,EMPLOYEE_ID, FIRST_NAME 
                OFFSET 1 ROW FETCH FIRST ROW ONLY;
            END IF;
    END P_SECOND_HEIGHET_SAL_EMP;
    
    FUNCTION FUN_IS_SALARAY_ABOVE_AVG_DEPT_SALARY(
        P_IN_EMP_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE
        ) RETURN VARCHAR2
        IS
        BEGIN
            SELECT 
            CASE WHEN SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES
                WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = P_IN_EMP_ID))
                THEN 'YES!'
                ELSE 'NO!'
            END
            INTO V_IS_SALARY_HIGH_THEN_DEPT_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = P_IN_EMP_ID;
            RETURN V_IS_SALARY_HIGH_THEN_DEPT_SALARY;
        END FUN_IS_SALARAY_ABOVE_AVG_DEPT_SALARY;
        
END PKG_FOR_PRACTICE;    
/
--CALLING THE PROCEDURES
DECLARE
    NUM1 NUMBER(2);
    NUM2 NUMBER(2);
    MUL NUMBER(4);
BEGIN
    NUM1:=9;
    NUM2:=10;
    PKG_FOR_PRACTICE.MULTIPLICATION (NUM1, NUM2, MUL);
    DBMS_OUTPUT.PUT_LINE(NUM1 || ' * ' || NUM2 || ' = ' || MUL);
END;
/
--CALLING SECOND PROCEDURE
DECLARE
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_EMP_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_SALARY EMPLOYEES.SALARY%TYPE;
    V_STATUS NUMBER :=0;
BEGIN
    PKG_FOR_PRACTICE.P_SECOND_HEIGHET_SAL_EMP(90, V_EMP_ID, V_EMP_NAME, V_SALARY, V_STATUS);
    DBMS_OUTPUT.PUT_LINE('STATUS: ' || V_STATUS);
    DBMS_OUTPUT.PUT_LINE('EMP_ID: ' || V_EMP_ID);
    DBMS_OUTPUT.PUT_LINE('NAME: ' || V_EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: ' || V_SALARY);
END;
/
--CALLING THE FUNCTION
SELECT PKG_FOR_PRACTICE.FUN_IS_SALARAY_ABOVE_AVG_DEPT_SALARY(101) FROM DUAL; 
/
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 101;
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
    
    
    
    
    
    
    
    
    
    
    
    
    
    