--User defined record type
--create a user defined record type and take three rows and find the heighest salary and store it in the record.
SET SERVEROUT ON
DECLARE
    TYPE  TYPE_EMP  IS RECORD
        (EMP_ID     EMPLOYEES.EMPLOYEE_ID%TYPE,
        MANAGER_ID  EMPLOYEES.MANAGER_ID%TYPE,
        FIRST_NAME  EMPLOYEES.FIRST_NAME%TYPE,
        SALARY      EMPLOYEES.SALARY%TYPE
        );
    V_UDRT_EMP TYPE_EMP;
BEGIN
    SELECT EMPLOYEE_ID, MANAGER_ID, FIRST_NAME,SALARY 
    INTO V_UDRT_EMP 
    FROM EMPLOYEES 
    ORDER BY SALARY DESC NULLS LAST FETCH FIRST ROW ONLY;
    
    DBMS_OUTPUT.PUT_LINE ('EMP_ID: ' || V_UDRT_EMP.EMP_ID);
    DBMS_OUTPUT.PUT_LINE ('MANAGER_ID: ' || V_UDRT_EMP.MANAGER_ID);
    DBMS_OUTPUT.PUT_LINE ('FIRST_NAME: ' || V_UDRT_EMP.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE ('SALARY: ' || V_UDRT_EMP.SALARY);
END;
/

SELECT * FROM EMPLOYEES;