CREATE TABLE MAIN_TABLE (
    EMP_ID NUMBER(2),
    EMP_NAME VARCHAR2(15),
    EMP_SALARY VARCHAR2 (6)
    );
    
CREATE TABLE BACKUP_TABLE (
    ID NUMBER(2),
    NAME VARCHAR2(15),
    SALARY VARCHAR2 (6)
    );

INSERT ALL
    INTO MAIN_TABLE VALUES(10, 'NASIR ULLAH', 30000)
    INTO MAIN_TABLE VALUES(11, 'MUSTANSIR', 20000)
    INTO MAIN_TABLE VALUES(12, 'JAVID AHMAD', 60000)
    INTO MAIN_TABLE VALUES(13, 'FAIZAN ALAM', 30000)
SELECT * FROM DUAL;
/
SELECT * FROM MAIN_TABLE;
/
CREATE OR REPLACE TRIGGER DEL_TRG
BEFORE DELETE ON MAIN_TABLE
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP_TABLE VALUES(:OLD.EMP_ID, :OLD.EMP_NAME, :OLD.EMP_SALARY);
END;
/
DELETE FROM MAIN_TABLE WHERE EMP_ID = 10;
/
DELETE FROM MAIN_TABLE WHERE EMP_ID = 11;
/
SELECT * FROM BACKUP_TABLE; 










